"""add_user_reading_profiles

Revision ID: 90217f974f93
Revises: f6c7d6035150
Create Date: 2026-06-23 15:45:13.270852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90217f974f93'
down_revision: Union[str, Sequence[str], None] = 'f6c7d6035150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reading_profiles',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=False),
    sa.Column('recent_history', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_reading_profiles_user_id'), 'user_reading_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reading_profiles_user_id'), table_name='user_reading_profiles')
    op.drop_table('user_reading_profiles')
    # ### end Alembic commands ###
