"""add embedding column to books

Revision ID: f6c7d6035150
Revises: a2f4a65fa9d7
Create Date: 2026-06-22 10:02:03.310622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c7d6035150'
down_revision: Union[str, Sequence[str], None] = 'a2f4a65fa9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('embedding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'embedding')
    # ### end Alembic commands ###
